FROM ubuntu as base

SHELL ["/bin/bash", "-c"] 

RUN apt-get update
RUN apt-get install -q -y git  \
    python3 \
    python3-pip \
    curl \ 
    npm

RUN npm install -g npm@v6.14.17

RUN npm install -g bower

FROM base as download_notebook

RUN git clone https://github.com/tainella/notebook

WORKDIR notebook
RUN pip install -q .

FROM download_notebook as npm_setup

ENV NVM_VERSION v0.33.11
ENV NODE_VERSION v14
ENV NVM_DIR /usr/local/nvm
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN mkdir $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

RUN source $NVM_DIR/nvm.sh
RUN nvm install $NODE_VERSION
RUN nvm use $NODE_VERSION

RUN node -v 
RUN npm -v

FROM npm_setup as jupyter_setup

RUN git clone https://github.com/tainella/jupyterlab

WORKDIR jupyterlab

#RUN node -v
#RUN npm -v
RUN pip install -e .
RUN jlpm install
RUN jlpm run build
RUN jplm run build:core
RUN jupyter lab build

FROM jupyter_setup as build
EXPOSE 8888

RUN mkdir -p /scripts
COPY extensions.sh /scripts

WORKDIR /scripts

RUN chmod +x extensions.sh
RUN ./extensions.sh

WORKDIR ..
WORKDIR /app

ENTRYPOINT jupyter lab --dev-mode --watch --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password=''
